### ISSUE TITLE
Guessed wrong for http://depsy.org/package/python/catsim

### ISSUE THREAD

**Issue by douglasrizzo** [total-impact/software#114]
It's a Python package that allow users to run simulations of [computerized adaptive tests](https://en.wikipedia.org/wiki/Computerized_adaptive_testing). I built it as part of my master's program.

**Comment by jsta** [comment]
Depsy is no longer being updated. See https://twitter.com/depsy_org/status/970376969782149120

**Comment by douglasrizzo** [comment]
OK, I'll close it then.
